apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assure-vbs-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: {{ .Values.hostnamePrefix }}-assure-vbs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: assure-vbs-service
                port:
                  number: 90
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: assure-vbs-ingress-grpc
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - grpc
  routes:
    - kind: Rule
      match: Host(`{{ .Values.hostnamePrefix }}-assure-vbs-grpc.com`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: assure-vbs-service
          port: 80
          scheme: h2c
