apiVersion: v1
kind: Service
metadata:
  name: admin-portal-service
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  selector:
    app: admin-portal
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001
