apiVersion: v1
kind: Service
metadata:
  name: engineresource-service
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  selector:
    app: engineresource
  ports:
    - name: http
      protocol: TCP
      port: 90
      targetPort: 90
    - name: grpc
      protocol: TCP
      port: 80
      targetPort: 80
