apiVersion: v1
kind: PersistentVolume
metadata:
  name: asr-grammar-cache
spec:
  accessModes:
  {{- if eq .Values.platform "minikube" }}
    - ReadWriteOnce
  {{- else if eq .Values.platform "cloud" }}
    - ReadWriteMany
  {{- end }}
  capacity:
    storage: 10Gi
  {{- if eq .Values.platform "minikube" }}
  hostPath:
  {{- else if eq .Values.platform "cloud" }}
  nfs:
    server: {{ .Values.volumeServer }}
  {{- end }}
    path: {{ .Values.volumeRoot }}/asr_grammar_cache
