apiVersion: v1
kind: Service
metadata:
  name: voice-verifier-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: voice-verifier
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 90
      targetPort: 90
    - name: grpc
      protocol: TCP
      port: 80
      targetPort: 80
