apiVersion: v1
kind: Service
metadata:
  name: license-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: license
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 5110
      targetPort: 5110
    - name: grpc
      protocol: TCP
      port: 5010
      targetPort: 5010
