apiVersion: apps/v1
kind: Deployment
metadata:
  name: binary-storage
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
  labels:
    app: binary-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binary-storage
  template:
    metadata:
      labels:
        app: binary-storage
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5110'
        {{- if .Values.global.linkerd.enabled }}
        linkerd.io/inject: enabled
        {{- end }}
    spec:
      containers:
        - name: binary-storage
          image: {{ .Values.image.repository | default .Values.global.image.repository }}/storage{{ .Values.image.tag | default .Values.global.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 5000
            - name: http
              containerPort: 5110
          readinessProbe:
            exec:
              command:
              - /usr/bin/storage
              - --healthcheck
            initialDelaySeconds: {{ .Values.global.lumenvox.service.startDelaySeconds }}
            periodSeconds: {{ .Values.global.lumenvox.probes.periodSeconds }}
          {{- if .Values.global.lumenvox.service.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
              - /usr/bin/storage
              - --healthcheck
            initialDelaySeconds: {{ .Values.global.lumenvox.service.startDelaySeconds }}
            periodSeconds: {{ .Values.global.lumenvox.probes.periodSeconds }}
          {{- end }}
          resources:
            requests:
              cpu: 350m
              memory: 300Mi
            {{- if .Values.global.lumenvox.enforceLimits }}
            limits:
              cpu: 550m
              memory: 650Mi
            {{- end }}
          envFrom:
            - configMapRef:
                name: lumenvox-configmap
            - configMapRef:
                name: timezone-configmap
            {{- if .Values.global.rabbitmq.auth.existingPasswordSecret }}
            - secretRef:
                name: {{ .Values.global.rabbitmq.auth.existingPasswordSecret }}
            {{- end }}
          env:
            {{- if not .Values.global.rabbitmq.auth.existingPasswordSecret }}
            - name: rabbitmq-password
              value: '{{ .Values.global.rabbitmq.auth.password }}'
            {{- end }}
            - name: GLOBAL_SETTINGS__CLUSTER_LOG_VERBOSITY
              value: '{{ .Values.global.lumenvox.loggingVerbosity }}'
            - name: RMQ_CA_CERTIFICATE
              value: '{{ .Values.global.rabbitmq.caCertificate }}'
            - name: RMQ_CLIENT_CERTIFICATE
              value: '{{ .Values.global.rabbitmq.clientCertificate }}'
            - name: RMQ_CLIENT_KEY
              value: '{{ .Values.global.rabbitmq.clientKey }}'
            - name: GLOBAL_SETTINGS__RABBITMQ_CONNECTION_STRING
              value: 'amqp{{ if .Values.global.rabbitmq.enableTLS }}s{{ end }}://{{ .Values.global.rabbitmq.connection.user }}:$(rabbitmq-password)@{{ .Values.global.rabbitmq.connection.url }}:{{ .Values.global.rabbitmq.connection.port }}'
            - name: GLOBAL_SETTINGS__RMQ_QUEUE_EXPIRE_MS
              value: '{{ .Values.global.lumenvox.rabbitmqQueueExpirationMs }}'
            - name: SERVICE_ADDRESSES__CONFIGURATION_SERVICE
              value: 'configuration-service.{{ default .Release.Namespace .Values.global.defaultNamespace }}:5000'
            - name: SERVICE_ADDRESSES__DEPLOYMENT_SERVICE
              value: 'deployment-service.{{ default .Release.Namespace .Values.global.defaultNamespace }}:5000'
            - name: LICENSE_SETTINGS__CLUSTER_GUID
              value: '{{ .Values.global.licensing.clusterGuid }}'

      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      initContainers:
        - name: wait-for-deployment-service
          image: {{ .Values.image.repository | default .Values.global.image.repository }}/cloud-init-tools{{ .Values.image.tag | default .Values.global.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
          command: ["curl2"]
          args: ["http://deployment-service.{{ default .Release.Namespace .Values.global.defaultNamespace }}:5110/health", "Deployment Service"]
