{{- if .Values.global.enableDiarization }}
{{- if .Values.global.lumenvox.metrics.enableEndpoints }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diarization-ingress
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  {{- if .Values.global.lumenvox.ingress.className }}
  ingressClassName: {{ .Values.global.lumenvox.ingress.className }}
  {{- end }}
  rules:
    - host: diarization{{ .Values.global.hostnameSuffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: diarization-service
                port:
                  name: http
{{- end }}
{{- end }}
