apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lumenvox-api-ingress-grpc
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
  {{- if or .Values.global.lumenvox.ingress.commonAnnotations .Values.global.lumenvox.ingress.grpcAnnotations }}
  annotations:
    {{- range .Values.global.lumenvox.ingress.commonAnnotations }}
      {{ .name }}: "{{ .value }}"
    {{- end }}
    {{- range .Values.global.lumenvox.ingress.grpcAnnotations }}
      {{ .name }}: "{{ .value }}"
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.global.lumenvox.ingress.className }}
  ingressClassName: {{ .Values.global.lumenvox.ingress.className }}
  {{- end }}
  rules:
    - host: lumenvox-api{{ .Values.global.hostnameSuffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lumenvox-api-service
                port:
                  name: grpc
  {{- if not .Values.global.lumenvox.ingress.disableTls }}
  tls:
    - secretName: speech-tls-secret
      hosts:
        - lumenvox-api{{ .Values.global.hostnameSuffix }}
  {{- end }}
