{{- if .Values.global.enableLumenvoxapiHealthcheck }}
{{- $ingressClassName := .Values.global.lumenvox.ingress.className -}}
{{- if ne $ingressClassName "istio" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lumenvox-api-ingress-health
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
  annotations:
    {{- include "lumenvox-common.nginxAnnotations" (dict "kind" "http" "root" $) }}
spec:
  {{- if $ingressClassName }}
  ingressClassName: {{ $ingressClassName }}
  {{- end }}
  {{- if not .Values.global.lumenvox.ingress.disableTls }}
  tls:
  - hosts:
    - "lumenvox-api{{ .Values.global.hostnameSuffix }}"
    secretName: {{ .Values.global.lumenvox.gateway.tlsSecretName }}
  {{- end }}
  rules:
  - host: "lumenvox-api{{ .Values.global.hostnameSuffix }}"
    http:
      paths:
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: lumenvox-api-service
            port:
              name: http
{{- else }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lumenvox-api-httproute-health
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  parentRefs:
    - name: {{ .Values.global.lumenvox.gateway.name }}
      namespace: {{ include "lumenvox-common.gatewayNamespace" . }}
      sectionName: web
  hostnames:
    - "lumenvox-api{{ .Values.global.hostnameSuffix }}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /health
      backendRefs:
        - name: lumenvox-api-service
          port: 5110
{{- end }}
{{- end }}
