{{- if .Values.global.lumenvox.metrics.enableEndpoints }}
{{- $ingressClassName := .Values.global.lumenvox.ingress.className -}}
{{- if ne $ingressClassName "istio" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: session-ingress
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  {{- if $ingressClassName }}
  ingressClassName: {{ $ingressClassName }}
  {{- end }}
  rules:
  - host: "session{{ .Values.global.hostnameSuffix }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: session-service
            port:
              name: http
{{- else }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: session-httproute
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  parentRefs:
    - name: {{ .Values.global.lumenvox.gateway.name }}
      namespace: {{ include "lumenvox-common.gatewayNamespace" . }}
      sectionName: web
  hostnames:
    - "session{{ .Values.global.hostnameSuffix }}"
  rules:
    - backendRefs:
        - name: session-service
          port: 5110
{{- end }}
{{- end }}
