{{- if .Values.global.lumenvox.metrics.enableEndpoints }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: license-ingress
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  {{- if .Values.global.lumenvox.ingress.className }}
  ingressClassName: {{ .Values.global.lumenvox.ingress.className }}
  {{- end }}
  rules:
    - host: license.{{ .Values.global.hostnameSuffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: license-service
                port:
                  number: 5110
{{- end }}
