apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deployment-portal-ingress
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
  {{- if or .Values.global.lumenvox.ingress.commonAnnotations .Values.global.lumenvox.ingress.httpAnnotations }}
  annotations:
    {{- range .Values.global.lumenvox.ingress.commonAnnotations }}
      {{ .name }}: "{{ .value }}"
    {{- end }}
    {{- range .Values.global.lumenvox.ingress.httpAnnotations }}
      {{ .name }}: "{{ .value }}"
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.global.lumenvox.ingress.className }}
  ingressClassName: {{ .Values.global.lumenvox.ingress.className }}
  {{- end }}
  rules:
    - host: deployment-portal{{ .Values.global.hostnameSuffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deployment-portal-service
                port:
                  name: portal
          {{- if .Values.global.lumenvox.metrics.enableEndpoints }}
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: admin-portal-service
                port:
                  name: http
          - path: /health  # Note this will override the deployment portal native /health page
            pathType: Prefix
            backend:
              service:
                name: admin-portal-service
                port:
                  name: http
          - path: /alive
            pathType: Prefix
            backend:
              service:
                name: admin-portal-service
                port:
                  name: http
          - path: /ready
            pathType: Prefix
            backend:
              service:
                name: admin-portal-service
                port:
                  name: http
          {{- end }}
  {{- if not .Values.global.lumenvox.ingress.disableTls }}
  tls:
    - secretName: speech-tls-secret
      hosts:
        - deployment-portal{{ .Values.global.hostnameSuffix }}
  {{- end }}
