{{- if .Values.prometheus.enabled }}
{{- $ingressClassName := .Values.global.lumenvox.ingress.className -}}
{{- if ne $ingressClassName "istio" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-alertmanager-ingress
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  {{- if $ingressClassName }}
  ingressClassName: {{ $ingressClassName }}
  {{- end }}
  rules:
  - host: "prometheus-alertmanager{{ .Values.global.hostnameSuffix }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lumenvox-prometheus-alertmanager
            port:
              number: 80
{{- else }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-alertmanager-httproute
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  parentRefs:
    - name: {{ .Values.global.lumenvox.gateway.name }}
      namespace: {{ include "lumenvox-common.gatewayNamespace" . }}
      sectionName: web
  hostnames:
    - "prometheus-alertmanager{{ .Values.global.hostnameSuffix }}"
  rules:
    - backendRefs:
        - name: lumenvox-prometheus-alertmanager
          port: 80
{{- end }}
{{- end }}
