apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-audio
  namespace: {{ default .Release.Namespace .Values.defaultNamespace }}
  labels:
    app: asr-audio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asr-audio
  template:
    metadata:
      labels:
        app: asr-audio
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5110'
        {{- if .Values.linkerd.enabled }}
        {{- if eq .Values.linkerd.ingressMode "nginx" }}
        linkerd.io/inject: enabled
        {{- else }}
        # Use traefik mode
        linkerd.io/inject: ingress
        {{- end }}
        {{- end }}
    spec:
      containers:
        - name: asr-audio
          image: {{ .Values.image.repository }}/cloud-asr-audio{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 5110
            - name: grpc
              containerPort: 5010
          readinessProbe:
            httpGet:
              path: /health
              port: 5110
            initialDelaySeconds: {{ .Values.lumenvox.service.startDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          {{- if .Values.lumenvox.service.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: 5110
            initialDelaySeconds: {{ .Values.lumenvox.service.startDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          {{- end }}
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
            {{- if .Values.lumenvox.enforceLimits }}
            limits:
              cpu: 100m
              memory: 50Mi
            {{- end }}
          envFrom:
            {{- if .Values.rabbitmq.auth.existingPasswordSecret }}
            - secretRef:
                name: {{ .Values.rabbitmq.auth.existingPasswordSecret }}
            {{- end }}
          env:
            - name: postgresql-password
              {{- if .Values.postgresql.existingSecret }}
              valueFrom:
                secretKeyRef:
                  key: postgresql-password
                  name: "{{ .Values.postgresql.existingSecret }}"
              {{- else }}
              value: "{{ .Values.postgresql.password }}"
              {{- end }}
            - name: DEPLOYMENT_DB_CONNECTION
              value: 'Server={{ .Values.postgresql.connection.url }};Port={{ .Values.postgresql.connection.port }};User ID={{ .Values.postgresql.connection.user }};Password=$(postgresql-password);Database=cloud_deployment_db;Integrated Security=true;Pooling=true;'
            - name: DEPLOYMENT_RECONNECTION_TIMEOUT_SECONDS
              value: '{{ .Values.lumenvox.deploymentReconnectionTimeoutSec }}'
            - name: SERVICE_ADDRESSES__DEPLOYMENT_SERVICE
              value: 'http://deployment-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
            {{ if .Values.licensing.showDebugOutput }}
            - name: SHOW_DEBUG_OUTPUT
              value: '{{ .Values.licensing.showDebugOutput }}'
            {{- end }}
            {{- if .Values.licensing.databaseHostOverride }}
            - name: DB_HOST_OVERRIDE
              value: '{{ .Values.licensing.databaseHostOverride }}'
            {{- end }}
            {{- if .Values.licensing.reportEndpoint }}
            {{- end }}
            - name: VERBOSE_DB_LOGGING
              value: '{{ .Values.licensing.verboseDbLogging }}'
            {{- if not .Values.rabbitmq.auth.existingPasswordSecret }}
            - name: rabbitmq-password
              value: '{{ .Values.rabbitmq.auth.password }}'
            {{- end }}
            - name: RABBIT_MQ_EASY_CONNECTION_STRING
              value: 'host={{ .Values.rabbitmq.connection.url }};port={{ .Values.rabbitmq.connection.port }};username={{ .Values.rabbitmq.connection.user }};password=$(rabbitmq-password);requestedHeartbeat=10'
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      initContainers:
        - name: wait-for-deployment-service
          image: {{ .Values.image.repository }}/cloud-init-tools{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["curl2"]
          args: ["http://deployment-service.{{ default .Release.Namespace .Values.defaultNamespace }}:90/health", "Deployment Service"]
