{{- $fineTunedEnabled := false }}
{{- range .Values.global.asrLanguages }}
{{- if .enableFineTuned }}{{ $fineTunedEnabled = true }}{{ end }}
{{- end }}
{{- if $fineTunedEnabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asr-site-packages-claim
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  accessModes:
  {{- if eq .Values.platform "minikube" }}
    - ReadWriteOnce
  {{- else if eq .Values.platform "cloud" }}
    - ReadWriteMany
  {{- end }}
  volumeName: asr-site-packages
  storageClassName: ""
  resources:
    requests:
      storage: 6Gi
{{- end }}