apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dict-claim
spec:
  accessModes:
  {{- if eq .Values.platform "minikube" }}
    - ReadWriteOnce
  {{- else if eq .Values.platform "cloud" }}
    - ReadWriteMany
  {{- end }}
  volumeName: dict
  storageClassName: ""
  resources:
    requests:
      storage: 6Gi
