apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itn-dist-packages-claim
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  accessModes:
  {{- if eq .Values.platform "minikube" }}
    - ReadWriteOnce
  {{- else if eq .Values.platform "cloud" }}
    - ReadWriteMany
  {{- end }}
  volumeName: itn-dist-packages
  storageClassName: ""
  resources:
    requests:
      storage: 6Gi
