{{- range .Values.global.asrLanguages }}
---
apiVersion: v1
kind: Service
metadata:
  name: asr-{{ .name }}-service
  namespace: {{ default $.Release.Namespace $.Values.global.defaultNamespace }}
spec:
  selector:
    app: asr-{{ .name }}
  ports:
    - name: http
      protocol: TCP
      port: 5110
      targetPort: 5110
    - name: grpc
      protocol: TCP
      port: 5010
      targetPort: 5010
{{- end }}
