apiVersion: v1
kind: Service
metadata:
  name: speech-api-service
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  selector:
    app: speech-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
