{{- range .Values.global.itnLanguages }}
---
apiVersion: v1
kind: Service
metadata:
  name: itn-{{ .name | replace "_" "-" }}-service
  namespace: {{ default $.Release.Namespace $.Values.global.defaultNamespace }}
spec:
  selector:
    app: itn-{{ .name | replace "_" "-" }}
  ports:
    - name: http
      port: 5110
      targetPort: http
{{- end }}