{{- if .Values.global.transcribeBatch.enabled }}
{{- range .Values.global.asrLanguages }}
---
apiVersion: v1
kind: Service
metadata:
  name: transcribe-batch-{{ .name | replace "_" "-" }}-service
  namespace: {{ default $.Release.Namespace $.Values.global.defaultNamespace }}
spec:
  selector:
    app: transcribe-batch-{{ .name | replace "_" "-" }}
  ports:
    - name: http
      port: 5110
      targetPort: http
{{- end }}
{{- end }}
