{{- range .Values.global.asrLanguages }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-{{ .name | replace "_" "-" }}
  namespace: {{ default $.Release.Namespace $.Values.global.defaultNamespace }}
  labels:
    app: asr-{{ .name | replace "_" "-" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asr-{{ .name | replace "_" "-" }}
  template:
    metadata:
      labels:
        app: asr-{{ .name | replace "_" "-" }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5110'
        {{- if $.Values.global.linkerd.enabled }}
        linkerd.io/inject: enabled
        {{- end }}
    spec:
      containers:
        - name: asr
          image: {{ $.Values.image.repository | default $.Values.global.image.repository }}/asr{{ $.Values.image.tag | default $.Values.global.image.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy | default $.Values.global.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5110
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ $.Values.global.lumenvox.service.startDelaySeconds }}
            periodSeconds: {{ $.Values.global.lumenvox.probes.periodSeconds }}
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 12
            periodSeconds: {{ $.Values.global.lumenvox.probes.periodSeconds }}
          {{- if $.Values.global.lumenvox.service.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ $.Values.global.lumenvox.service.startDelaySeconds }}
            periodSeconds: {{ $.Values.global.lumenvox.probes.periodSeconds }}
          {{- end }}
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
            {{- if or $.Values.global.lumenvox.enforceLimits .enableFineTuned }}
            limits:
              {{- if $.Values.global.lumenvox.enforceLimits }}
              cpu: 100m
              memory: 50Mi
              {{- end }}
              {{- if .enableFineTuned }}
              nvidia.com/gpu: "1"
              {{- end }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: timezone-configmap
            {{- if $.Values.global.rabbitmq.auth.existingPasswordSecret }}
            - secretRef:
                name: {{ $.Values.global.rabbitmq.auth.existingPasswordSecret }}
            {{- end }}
            {{- if $.Values.global.redis.auth.existingSecret }}
            - secretRef:
                name: {{ $.Values.global.redis.auth.existingSecret }}
            {{- end }}
          env:
            {{- if not $.Values.global.rabbitmq.auth.existingPasswordSecret }}
            - name: rabbitmq-password
              value: '{{ $.Values.global.rabbitmq.auth.password }}'
            {{- end }}
            {{- if not $.Values.global.redis.auth.existingSecret }}
            - name: redis-password
              value: '{{ $.Values.global.redis.auth.password }}'
            {{- end }}
            - name: GLOBAL_SETTINGS__CLUSTER_LOG_VERBOSITY
              value: '{{ $.Values.global.lumenvox.loggingVerbosity }}'
            - name: LICENSE_SETTINGS__CLUSTER_GUID
              value: '{{ $.Values.global.licensing.clusterGuid }}'  
            - name: REDIS_SETTINGS__DEFAULT_TTL
              value: '{{ $.Values.global.lumenvox.redisTtl }}'
            - name: RMQ_CA_CERTIFICATE
              value: '{{ $.Values.global.rabbitmq.caCertificate }}'
            - name: RMQ_CLIENT_CERTIFICATE
              value: '{{ $.Values.global.rabbitmq.clientCertificate }}'
            - name: RMQ_CLIENT_KEY
              value: '{{ $.Values.global.rabbitmq.clientKey }}'
            - name: GLOBAL_SETTINGS__RABBITMQ_CONNECTION_STRING
              value: 'amqp{{ if $.Values.global.rabbitmq.enableTLS }}s{{ end }}://{{ $.Values.global.rabbitmq.connection.user }}:$(rabbitmq-password)@{{ $.Values.global.rabbitmq.connection.url }}:{{ $.Values.global.rabbitmq.connection.port }}'
            - name: GLOBAL_SETTINGS__RMQ_QUEUE_EXPIRE_MS
              value: '{{ $.Values.global.lumenvox.rabbitmqQueueExpirationMs }}'
            - name: SERVICE_ADDRESSES__CONFIGURATION_SERVICE
              value: 'http://configuration-service.{{ default $.Release.Namespace $.Values.global.defaultNamespace }}'
            - name: SERVICE_ADDRESSES__DEPLOYMENT_SERVICE
              value: 'http://deployment-service.{{ default $.Release.Namespace $.Values.global.defaultNamespace }}'
            - name: ASR_SETTINGS__SERVICE_LANGUAGE
              value: '{{ .name }}'
            - name: ASR_SETTINGS__CACHE_MAX_ENTRIES
              value: '{{ $.Values.asr.cacheMaxEntries }}'
            - name: ASR_SETTINGS__CACHE_MAX_SIZE_MB
              value: '{{ $.Values.asr.cacheMaxSizeMb }}'
            {{- if .enableFineTuned }}
            - name: ASR_SETTINGS__ENABLE_FINE_TUNED
              value: '1'
            {{- end }}
            - name: GOLANG_PROTOBUF_REGISTRATION_CONFLICT
              value: 'ignore'
          volumeMounts:
            - mountPath: /usr/local/lib/python3.8/dist-packages
              name: asr-dist-packages
            {{- if .enableFineTuned }}
            - mountPath: /finetuned/venv/lib/python3.8/site-packages
              name: asr-site-packages
            {{- end }}
            - mountPath: /EuropaAsrModels
              name: europamodels
            - mountPath: /var/lumenvox/cache
              name: europa-cache
            - mountPath: /BackendModels
              name: backendmodels
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- range $.Values.global.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      initContainers:
        - name: wait-for-deployment-service
          image: {{ $.Values.image.repository | default $.Values.global.image.repository }}/cloud-init-tools{{ $.Values.image.tag | default $.Values.global.image.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy | default $.Values.global.image.pullPolicy }}
          command: ["curl2"]
          args: ["http://deployment-service.{{ default $.Release.Namespace $.Values.global.defaultNamespace }}:5110/health", "Deployment Service"]
        - name: wait-for-resource-manager
          image: {{ $.Values.image.repository | default $.Values.global.image.repository }}/cloud-init-tools{{ $.Values.image.tag | default $.Values.global.image.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy | default $.Values.global.image.pullPolicy }}
          command: ["curl2"]
          args: ["http://resource-service.{{ default $.Release.Namespace $.Values.global.defaultNamespace }}:5110/health", "Resource Manager Service"]
      volumes:
        - name: asr-dist-packages
          persistentVolumeClaim:
            claimName: asr-dist-packages-claim
            readOnly: false
        {{- if .enableFineTuned }}
        - name: asr-site-packages
          persistentVolumeClaim:
            claimName: asr-site-packages-claim
            readOnly: false
        {{- end }}
        - name: europamodels
          persistentVolumeClaim:
            claimName: europamodels-claim
            readOnly: false
        - name: backendmodels
          persistentVolumeClaim:
            claimName: backendmodels-claim
            readOnly: false
        - name: europa-cache
          persistentVolumeClaim:
            claimName: europa-cache-claim
            readOnly: false
{{- end }}
