apiVersion: v2
name: lumenvox-speech
description: LumenVox Speech Helm chart for Kubernetes
type: application
version: 8.0.0
appVersion: "8.0.0"
home: https://lumenvox.com
annotations:
  artifacthub.io/containsSecurityUpdates: true
  artifacthub.io/images: |
    - name: asr
      image: lumenvox/asr:8.0
    - name: diarization
      image: lumenvox/diarization:8.0
    - name: cloud-init-tools
      image: lumenvox/cloud-init-tools:8.0
    - name: cloud-logging-sidecar
      image: lumenvox/cloud-logging-sidecar:8.0
    - name: grammar
      image: lumenvox/grammar:8.0
    - name: itn
      image: lumenvox/itn:8.0
    - name: lid
      image: lumenvox/lid:8.0
    - name: lumenvox-api
      image: lumenvox/lumenvox-api:8.0
    - name: neural-tts
      image: lumenvox/neural-tts:8.0
    - name: neuron
      image: lumenvox/neuron:8.0
    - name: nlu
      image: lumenvox/nlu:8.0
    - name: reporting-api
      image: lumenvox/reporting-api:8.0
    - name: session
      image: lumenvox/session:8.0
    - name: tts
      image: lumenvox/tts:8.0
    - name: vad
      image: lumenvox/vad:8.0
