apiVersion: v2
name: lumenvox-vb
description: LumenVox Voice Biometrics Helm chart for Kubernetes
type: application
version: 8.0.0
appVersion: "8.0.0"
home: https://lumenvox.com
annotations:
  artifacthub.io/containsSecurityUpdates: true
  artifacthub.io/images: |
    - name: audit
      image: lumenvox/audit:8.0
    - name: biometric-active
      image: lumenvox/biometric-active:8.0
    - name: biometric-api
      image: lumenvox/biometric-api:8.0
    - name: biometric-identity
      image: lumenvox/biometric-identity:8.0
    - name: cloud-init-tools
      image: lumenvox/cloud-init-tools:8.0
    - name: reporting-bio-api
      image: lumenvox/reporting-bio-api:8.0
    - name: reporting
      image: lumenvox/reporting:8.0
    - name: transaction
      image: lumenvox/transaction:8.0
