apiVersion: v1
kind: ConfigMap
metadata:
  name: lumenvox-configmap
  namespace: '{{ default .Release.Namespace .Values.defaultNamespace }}'
data:
  DOCKER_REGISTRY: '{{ .Values.image.repository }}'
  COMPOSE_PROJECT_NAME: '{{ .Values.composeProjectName }}'
  DB_USER_COMMON: '{{ .Values.postgresql.connection.user }}'
  DB_PASS_COMMON: '{{ .Values.postgresql.connection.password }}'
  DEPLOYMENT_POSTGRES_CONNECTION_STRING: 'Server={{ .Values.postgresql.connection.url }};Port={{ .Values.postgresql.connection.port }};User ID={{ .Values.postgresql.connection.user }};Password={{ .Values.postgresql.connection.password }};Database=cloud_deployment_db;Integrated Security=true;Pooling=true;'
  RABBIT_MQ_CONNECTION_STRING: 'amqp://{{ .Values.rabbitmq.connection.user }}:{{ .Values.rabbitmq.connection.password }}@{{ .Values.rabbitmq.connection.url }}:{{ .Values.rabbitmq.connection.port }}'
  RABBIT_MQ_EASY_CONNECTION_STRING: 'host={{ .Values.rabbitmq.connection.url }};port={{ .Values.rabbitmq.connection.port }};username={{ .Values.rabbitmq.connection.user }};password={{ .Values.rabbitmq.connection.password }};requestedHeartbeat=10'
  WEB_USER_COMMON: '{{ .Values.web.commonUser }}'
  WEB_PASS_COMMON: '{{ .Values.web.commonPass }}'
  MASTER_ENCRYPTION_KEY: '{{ .Values.encryption.masterEncryptionKey }}'
  ENABLE_ELASTICSEARCH: '{{ .Values.logging.enableElasticsearch }}'
  RUN_DATABASE_MIGRATIONS: '{{ .Values.postgresql.runMigrations }}'
  EXIT_AFTER_DATABASE_MIGRATIONS: '{{ .Values.postgresql.exitAfterMigrations }}'
  SERILOG_DEFAULT_LOGGING_LEVEL: '{{ .Values.logging.defaultLevel }}'
  SERILOG_OVERRIDE_MICROSOFT_LOGGING_LEVEL: '{{ .Values.logging.overrideMicrosoftLevel }}'
  SERILOG_OVERRIDE_SYSTEM_LOGGING_LEVEL: '{{ .Values.logging.overrideSystemLevel }}'
  SERILOG_OVERRIDE_GRPC_LOGGING_LEVEL: '{{ .Values.logging.overrideGrpcLevel }}'
  Audit: '{{ .Values.enableAudit }}'
  DB_COMMAND_TIMEOUT_SECONDS: '{{ .Values.postgresql.commandTimeoutSeconds }}'
  LOCAL_CACHE_REFRESH_SECONDS: '21600'
  ASPNETCORE_ENVIRONMENT: 'Production'
  ASPNETCORE_Kestrel__EndPoints__Http1__Url: 'http://+:90'
  ASPNETCORE_Kestrel__EndPoints__Http1__Protocols: 'Http1'
  ASPNETCORE_Kestrel__EndPoints__Http2__Url: 'http://+:80'
  ASPNETCORE_Kestrel__EndPoints__Http3__Url: 'https://+:443'
  HTTPS_CERTIFICATE: '{{ .Values.https.cert }}'
  HTTPS_CERTIFICATE_KEY: '{{ .Values.https.certKey }}'
  HTTPS_CERTIFICATE_PASSWORD: '{{ .Values.https.certPassword }}'
  USE_SELF_SIGNED_CERTIFICATE: '{{ .Values.https.useSelfSignedCert }}'
  APPLICATION_DOMAIN: '{{ .Values.https.applicationDomain }}'
  ServiceAddresses__DeploymentService: 'http://deployment-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__ConfigurationService: 'http://configuration-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__EngineResourceService: 'http://engineresource-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__VoiceVerifierService: 'http://voice-verifier-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__AssureVbs: 'http://assure-vbs-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__BinaryStorageService: 'http://binarystorage-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__AssureIdentityService: 'http://assure-identity-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__LicenseService: 'http://license-service.{{ default .Release.Namespace .Values.defaultNamespace }}:5010'
  ServiceAddresses__TransactionService: 'http://transaction-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__AuditService: 'http://audit-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__ReportingService: 'http://reporting-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__ReportingApiService: 'http://reporting-api-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  ServiceAddresses__ManagementApiService: 'http://management-api-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  DbSettings__PostgresConnectionString:  'Server={{ .Values.postgresql.connection.url }};Port={{ .Values.postgresql.connection.port }};User ID={{ .Values.postgresql.connection.user }};Password={{ .Values.postgresql.connection.password }};Database=cloud_deployment_db;Integrated Security=true;Pooling=true;'
  DbSettings__CommandTimeoutSeconds: '{{ .Values.postgresql.commandTimeoutSeconds }}'
  EncryptionSettings__MasterKey: '{{ .Values.encryption.masterEncryptionKey }}'
  ENV_SERVICE_START_DELAY_SECONDS: '{{ .Values.lumenvox.service.startDelaySeconds }}'
  EncryptionSettings__UseEncryption: '{{ .Values.encryption.useEncryption }}'
  EncryptionSettings__MasterKeyProvider: '{{ .Values.encryption.masterKeyProvider }}'
  ConnectionStrings__PostgresConnection: 'Server={{ .Values.postgresql.connection.url }};Port={{ .Values.postgresql.connection.port }};User ID={{ .Values.postgresql.connection.user }};Password={{ .Values.postgresql.connection.password }};Database=cloud_deployment_db;Integrated Security=true;Pooling=true;'
  {{- if .Values.mockData.enabled }}
  MOCK_TEST_DATA: '{{ .Values.mockData.testDataString }}'
  MockDataSettings__MasterKeysJson: '{{ .Values.mockData.jsonKeys.master }}'
  MockDataSettings__CustomerKeysJson: '{{ .Values.mockData.jsonKeys.customer }}'
  MockDataSettings__EmergencyPublicKeysJson: '{{ .Values.mockData.jsonKeys.emergencyPublic }}'
  {{- end }}
  DASHBOARD_POSTGRES_CONNECTION_STRING: 'Server={{ .Values.postgresql.connection.url }};Port={{ .Values.postgresql.connection.port }};User ID={{ .Values.postgresql.connection.user }};Password={{ .Values.postgresql.connection.password }};Database=cloud_dashboard_db;Integrated Security=true;Pooling=true;'
  POSTGRES_DB: '{{ .Values.postgresql.postgresDb }}'
  DEPLOYMENT_RECONNECTION_TIMEOUT_SEC: '{{ .Values.lumenvox.deploymentReconnectionTimeoutSec }}'
