apiVersion: v1
kind: ConfigMap
metadata:
  name: lumenvox-configmap
  namespace: '{{ default .Release.Namespace .Values.defaultNamespace }}'
data:
  ASPNETCORE_ENVIRONMENT: 'Production'
  ENABLE_ELASTICSEARCH: '{{ .Values.logging.enableElasticsearch }}'
  SERILOG_DEFAULT_LOGGING_LEVEL: '{{ .Values.logging.defaultLevel }}'
  SERILOG_OVERRIDE_MICROSOFT_LOGGING_LEVEL: '{{ .Values.logging.overrideMicrosoftLevel }}'
  SERILOG_OVERRIDE_SYSTEM_LOGGING_LEVEL: '{{ .Values.logging.overrideSystemLevel }}'
  SERILOG_OVERRIDE_GRPC_LOGGING_LEVEL: '{{ .Values.logging.overrideGrpcLevel }}'
  ASPNETCORE_URLS: 'http://+:80'
  RABBIT_RETRYING_TIME_SECONDS: '{{ .Values.rabbitmq.retryTime }}'
  LOCAL_CACHE_REFRESH_SECONDS: '21600'
  SERVICE_ADDRESSES__ASSURE_API: 'http://assure-api-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  SERVICE_ADDRESSES__TRANSACTION_SERVICE: 'http://transaction-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  SERVICE_ADDRESSES__AUDIT_SERVICE: 'http://audit-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  SERVICE_ADDRESSES__REPORTING_API: 'http://reporting-api-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  SERVICE_ADDRESSES__MANAGEMENT_API: 'http://management-api-service.{{ default .Release.Namespace .Values.defaultNamespace }}'
  {{- if .Values.mockData.enabled }}
  MOCK_TEST_DATA: '{{ .Values.mockData.testDataString }}'
  MockDataSettings__MasterKeysJson: '{{ .Values.mockData.jsonKeys.master }}'
  MockDataSettings__CustomerKeysJson: '{{ .Values.mockData.jsonKeys.customer }}'
  MockDataSettings__EmergencyPublicKeysJson: '{{ .Values.mockData.jsonKeys.emergencyPublic }}'
  {{- end }}
