apiVersion: v1
kind: Secret
metadata:
  name: lumenvox-azurecr-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.docker.registryPullSecret }}
