{{/*apiVersion: v1*/}}
{{/*kind: Secret*/}}
{{/*metadata:*/}}
{{/*  namespace: {{ default .Release.Namespace .Values.defaultNamespace }}*/}}
{{/*  name: rabbitmq-secret*/}}
{{/*type: Opaque*/}}
{{/*data:*/}}
{{/*  rabbitmq-password: {{ .Values.rabbitmq.connection.password | b64enc }}*/}}
{{/*---*/}}
{{/*{{- if .Values.grafana.enabled }}*/}}
{{/*apiVersion: v1*/}}
{{/*kind: Secret*/}}
{{/*metadata:*/}}
{{/*  namespace: {{ default .Release.Namespace .Values.defaultNamespace }}*/}}
{{/*  name: grafana-secret*/}}
{{/*type: Opaque*/}}
{{/*data:*/}}
{{/*  adminUser: {{ .Values.grafana.adminUser | b64enc }}*/}}
{{/*  adminPassword: {{ .Values.grafana.adminPassword | b64enc }}*/}}
{{/*{{- end }}*/}}
{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: Secret*/}}
{{/*metadata:*/}}
{{/*  name: prometheus-grafana-secret*/}}
{{/*  namespace: {{ default .Release.Namespace .Values.defaultNamespace }}*/}}
{{/*type: Opaque*/}}
{{/*stringData:*/}}
{{/*  other_datasource.yaml: |-*/}}
{{/*    apiVersion: 1*/}}
{{/*    datasources:*/}}
{{/*      - name: Prometheus*/}}
{{/*        type: prometheus*/}}
{{/*        url: {{ .Values.prometheus.connection.url }}*/}}
{{/*---*/}}
{{/*{{- if .Values.linkerd.dashboard.enabled }}*/}}
{{/*apiVersion: v1*/}}
{{/*kind: Secret*/}}
{{/*type: Opaque*/}}
{{/*metadata:*/}}
{{/*  name: web-ingress-auth*/}}
{{/*  namespace: {{ .Values.linkerd.dashboard.namespace }}*/}}
{{/*data:*/}}
{{/*  auth: {{ .Values.linkerd.dashboard.ingressSecret }}*/}}
{{/*{{- end }}*/}}
